/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DecentralizedTenderChain {
  export type BidStruct = {
    tenderId: BigNumberish;
    bidder: AddressLike;
    encryptedBidHash: BytesLike;
    price: BigNumberish;
    priceScore: BigNumberish;
    financialStrength: BigNumberish;
    pastExperience: BigNumberish;
    performanceFeedback: BigNumberish;
    technicalCapability: BigNumberish;
    compliance: BigNumberish;
    proposalQuality: BigNumberish;
    totalScore: BigNumberish;
    status: BigNumberish;
    submittedAt: BigNumberish;
    revealedAt: BigNumberish;
    exists: boolean;
  };

  export type BidStructOutput = [
    tenderId: bigint,
    bidder: string,
    encryptedBidHash: string,
    price: bigint,
    priceScore: bigint,
    financialStrength: bigint,
    pastExperience: bigint,
    performanceFeedback: bigint,
    technicalCapability: bigint,
    compliance: bigint,
    proposalQuality: bigint,
    totalScore: bigint,
    status: bigint,
    submittedAt: bigint,
    revealedAt: bigint,
    exists: boolean
  ] & {
    tenderId: bigint;
    bidder: string;
    encryptedBidHash: string;
    price: bigint;
    priceScore: bigint;
    financialStrength: bigint;
    pastExperience: bigint;
    performanceFeedback: bigint;
    technicalCapability: bigint;
    compliance: bigint;
    proposalQuality: bigint;
    totalScore: bigint;
    status: bigint;
    submittedAt: bigint;
    revealedAt: bigint;
    exists: boolean;
  };

  export type TenderStruct = {
    id: BigNumberish;
    officer: AddressLike;
    title: string;
    ipfsHash: string;
    budget: BigNumberish;
    deadline: BigNumberish;
    minScore: BigNumberish;
    msmeQuota: boolean;
    status: BigNumberish;
    winner: AddressLike;
    winnerPrice: BigNumberish;
    winnerScore: BigNumberish;
    bidCount: BigNumberish;
    createdAt: BigNumberish;
    evaluatedAt: BigNumberish;
  };

  export type TenderStructOutput = [
    id: bigint,
    officer: string,
    title: string,
    ipfsHash: string,
    budget: bigint,
    deadline: bigint,
    minScore: bigint,
    msmeQuota: boolean,
    status: bigint,
    winner: string,
    winnerPrice: bigint,
    winnerScore: bigint,
    bidCount: bigint,
    createdAt: bigint,
    evaluatedAt: bigint
  ] & {
    id: bigint;
    officer: string;
    title: string;
    ipfsHash: string;
    budget: bigint;
    deadline: bigint;
    minScore: bigint;
    msmeQuota: boolean;
    status: bigint;
    winner: string;
    winnerPrice: bigint;
    winnerScore: bigint;
    bidCount: bigint;
    createdAt: bigint;
    evaluatedAt: bigint;
  };
}

export interface DecentralizedTenderChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeOfficer"
      | "authorizedOfficers"
      | "bids"
      | "blacklistVendor"
      | "blacklistedVendors"
      | "cancelTender"
      | "createTender"
      | "evaluateTender"
      | "evaluateWithWinner"
      | "getBid"
      | "getTender"
      | "getTenderCount"
      | "isAuthorizedOfficer"
      | "isRegisteredVendor"
      | "owner"
      | "pause"
      | "paused"
      | "registerVendor"
      | "registeredVendors"
      | "renounceOwnership"
      | "revealBid"
      | "revokeOfficer"
      | "submitBid"
      | "tenders"
      | "transferOwnership"
      | "unpause"
      | "updateTender"
      | "whitelistVendor"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidRevealed"
      | "BidSubmitted"
      | "OfficerAuthorized"
      | "OfficerRevoked"
      | "OwnershipTransferred"
      | "Paused"
      | "TenderCreated"
      | "TenderEvaluated"
      | "TenderStatusChanged"
      | "TenderUpdated"
      | "Unpaused"
      | "VendorBlacklisted"
      | "VendorRegistered"
      | "VendorWhitelisted"
      | "WinnerDeclared"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeOfficer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedOfficers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bids",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistVendor",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistedVendors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTender",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTender",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "evaluateTender",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "evaluateWithWinner",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBid",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTender",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTenderCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedOfficer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegisteredVendor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerVendor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredVendors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealBid",
    values: [BigNumberish, BigNumberish, BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeOfficer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tenders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateTender",
    values: [BigNumberish, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistVendor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "authorizeOfficer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedOfficers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blacklistVendor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistedVendors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evaluateTender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evaluateWithWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTender", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTenderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedOfficer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredVendor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerVendor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredVendors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revealBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeOfficer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tenders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistVendor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace BidRevealedEvent {
  export type InputTuple = [
    tenderId: BigNumberish,
    bidder: AddressLike,
    price: BigNumberish,
    totalScore: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tenderId: bigint,
    bidder: string,
    price: bigint,
    totalScore: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tenderId: bigint;
    bidder: string;
    price: bigint;
    totalScore: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [
    tenderId: BigNumberish,
    bidder: AddressLike,
    encryptedBidHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tenderId: bigint,
    bidder: string,
    encryptedBidHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tenderId: bigint;
    bidder: string;
    encryptedBidHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfficerAuthorizedEvent {
  export type InputTuple = [officer: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [officer: string, timestamp: bigint];
  export interface OutputObject {
    officer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfficerRevokedEvent {
  export type InputTuple = [officer: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [officer: string, timestamp: bigint];
  export interface OutputObject {
    officer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TenderCreatedEvent {
  export type InputTuple = [
    tenderId: BigNumberish,
    officer: AddressLike,
    title: string,
    ipfsHash: string,
    budget: BigNumberish,
    deadline: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tenderId: bigint,
    officer: string,
    title: string,
    ipfsHash: string,
    budget: bigint,
    deadline: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tenderId: bigint;
    officer: string;
    title: string;
    ipfsHash: string;
    budget: bigint;
    deadline: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TenderEvaluatedEvent {
  export type InputTuple = [
    tenderId: BigNumberish,
    triggeredBy: AddressLike,
    totalBids: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tenderId: bigint,
    triggeredBy: string,
    totalBids: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tenderId: bigint;
    triggeredBy: string;
    totalBids: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TenderStatusChangedEvent {
  export type InputTuple = [
    tenderId: BigNumberish,
    newStatus: BigNumberish,
    changedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tenderId: bigint,
    newStatus: bigint,
    changedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tenderId: bigint;
    newStatus: bigint;
    changedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TenderUpdatedEvent {
  export type InputTuple = [
    tenderId: BigNumberish,
    officer: AddressLike,
    changes: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tenderId: bigint,
    officer: string,
    changes: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tenderId: bigint;
    officer: string;
    changes: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VendorBlacklistedEvent {
  export type InputTuple = [
    vendor: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [vendor: string, reason: string, timestamp: bigint];
  export interface OutputObject {
    vendor: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VendorRegisteredEvent {
  export type InputTuple = [vendor: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [vendor: string, timestamp: bigint];
  export interface OutputObject {
    vendor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VendorWhitelistedEvent {
  export type InputTuple = [vendor: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [vendor: string, timestamp: bigint];
  export interface OutputObject {
    vendor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerDeclaredEvent {
  export type InputTuple = [
    tenderId: BigNumberish,
    winner: AddressLike,
    price: BigNumberish,
    totalScore: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tenderId: bigint,
    winner: string,
    price: bigint,
    totalScore: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tenderId: bigint;
    winner: string;
    price: bigint;
    totalScore: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DecentralizedTenderChain extends BaseContract {
  connect(runner?: ContractRunner | null): DecentralizedTenderChain;
  waitForDeployment(): Promise<this>;

  interface: DecentralizedTenderChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeOfficer: TypedContractMethod<
    [_officer: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedOfficers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  bids: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        tenderId: bigint;
        bidder: string;
        encryptedBidHash: string;
        price: bigint;
        priceScore: bigint;
        financialStrength: bigint;
        pastExperience: bigint;
        performanceFeedback: bigint;
        technicalCapability: bigint;
        compliance: bigint;
        proposalQuality: bigint;
        totalScore: bigint;
        status: bigint;
        submittedAt: bigint;
        revealedAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  blacklistVendor: TypedContractMethod<
    [_vendor: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;

  blacklistedVendors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  cancelTender: TypedContractMethod<
    [_tenderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createTender: TypedContractMethod<
    [
      _title: string,
      _ipfsHash: string,
      _budget: BigNumberish,
      _deadline: BigNumberish,
      _minScore: BigNumberish,
      _msmeQuota: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  evaluateTender: TypedContractMethod<
    [_tenderId: BigNumberish],
    [void],
    "view"
  >;

  evaluateWithWinner: TypedContractMethod<
    [_tenderId: BigNumberish, _winner: AddressLike, _winnerScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBid: TypedContractMethod<
    [_tenderId: BigNumberish, _bidder: AddressLike],
    [DecentralizedTenderChain.BidStructOutput],
    "view"
  >;

  getTender: TypedContractMethod<
    [_tenderId: BigNumberish],
    [DecentralizedTenderChain.TenderStructOutput],
    "view"
  >;

  getTenderCount: TypedContractMethod<[], [bigint], "view">;

  isAuthorizedOfficer: TypedContractMethod<
    [_officer: AddressLike],
    [boolean],
    "view"
  >;

  isRegisteredVendor: TypedContractMethod<
    [_vendor: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerVendor: TypedContractMethod<
    [_vendor: AddressLike],
    [void],
    "nonpayable"
  >;

  registeredVendors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revealBid: TypedContractMethod<
    [
      _tenderId: BigNumberish,
      _price: BigNumberish,
      _scoreHashes: BigNumberish[],
      _nonce: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  revokeOfficer: TypedContractMethod<
    [_officer: AddressLike],
    [void],
    "nonpayable"
  >;

  submitBid: TypedContractMethod<
    [_tenderId: BigNumberish, _encryptedBidHash: BytesLike],
    [void],
    "nonpayable"
  >;

  tenders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        officer: string;
        title: string;
        ipfsHash: string;
        budget: bigint;
        deadline: bigint;
        minScore: bigint;
        msmeQuota: boolean;
        status: bigint;
        winner: string;
        winnerPrice: bigint;
        winnerScore: bigint;
        bidCount: bigint;
        createdAt: bigint;
        evaluatedAt: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateTender: TypedContractMethod<
    [
      _tenderId: BigNumberish,
      _title: string,
      _ipfsHash: string,
      _budget: BigNumberish,
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  whitelistVendor: TypedContractMethod<
    [_vendor: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeOfficer"
  ): TypedContractMethod<[_officer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedOfficers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "bids"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        tenderId: bigint;
        bidder: string;
        encryptedBidHash: string;
        price: bigint;
        priceScore: bigint;
        financialStrength: bigint;
        pastExperience: bigint;
        performanceFeedback: bigint;
        technicalCapability: bigint;
        compliance: bigint;
        proposalQuality: bigint;
        totalScore: bigint;
        status: bigint;
        submittedAt: bigint;
        revealedAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "blacklistVendor"
  ): TypedContractMethod<
    [_vendor: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "blacklistedVendors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "cancelTender"
  ): TypedContractMethod<[_tenderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTender"
  ): TypedContractMethod<
    [
      _title: string,
      _ipfsHash: string,
      _budget: BigNumberish,
      _deadline: BigNumberish,
      _minScore: BigNumberish,
      _msmeQuota: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "evaluateTender"
  ): TypedContractMethod<[_tenderId: BigNumberish], [void], "view">;
  getFunction(
    nameOrSignature: "evaluateWithWinner"
  ): TypedContractMethod<
    [_tenderId: BigNumberish, _winner: AddressLike, _winnerScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBid"
  ): TypedContractMethod<
    [_tenderId: BigNumberish, _bidder: AddressLike],
    [DecentralizedTenderChain.BidStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTender"
  ): TypedContractMethod<
    [_tenderId: BigNumberish],
    [DecentralizedTenderChain.TenderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTenderCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAuthorizedOfficer"
  ): TypedContractMethod<[_officer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRegisteredVendor"
  ): TypedContractMethod<[_vendor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerVendor"
  ): TypedContractMethod<[_vendor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredVendors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealBid"
  ): TypedContractMethod<
    [
      _tenderId: BigNumberish,
      _price: BigNumberish,
      _scoreHashes: BigNumberish[],
      _nonce: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeOfficer"
  ): TypedContractMethod<[_officer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitBid"
  ): TypedContractMethod<
    [_tenderId: BigNumberish, _encryptedBidHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tenders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        officer: string;
        title: string;
        ipfsHash: string;
        budget: bigint;
        deadline: bigint;
        minScore: bigint;
        msmeQuota: boolean;
        status: bigint;
        winner: string;
        winnerPrice: bigint;
        winnerScore: bigint;
        bidCount: bigint;
        createdAt: bigint;
        evaluatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTender"
  ): TypedContractMethod<
    [
      _tenderId: BigNumberish,
      _title: string,
      _ipfsHash: string,
      _budget: BigNumberish,
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "whitelistVendor"
  ): TypedContractMethod<[_vendor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BidRevealed"
  ): TypedContractEvent<
    BidRevealedEvent.InputTuple,
    BidRevealedEvent.OutputTuple,
    BidRevealedEvent.OutputObject
  >;
  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OfficerAuthorized"
  ): TypedContractEvent<
    OfficerAuthorizedEvent.InputTuple,
    OfficerAuthorizedEvent.OutputTuple,
    OfficerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OfficerRevoked"
  ): TypedContractEvent<
    OfficerRevokedEvent.InputTuple,
    OfficerRevokedEvent.OutputTuple,
    OfficerRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "TenderCreated"
  ): TypedContractEvent<
    TenderCreatedEvent.InputTuple,
    TenderCreatedEvent.OutputTuple,
    TenderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TenderEvaluated"
  ): TypedContractEvent<
    TenderEvaluatedEvent.InputTuple,
    TenderEvaluatedEvent.OutputTuple,
    TenderEvaluatedEvent.OutputObject
  >;
  getEvent(
    key: "TenderStatusChanged"
  ): TypedContractEvent<
    TenderStatusChangedEvent.InputTuple,
    TenderStatusChangedEvent.OutputTuple,
    TenderStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "TenderUpdated"
  ): TypedContractEvent<
    TenderUpdatedEvent.InputTuple,
    TenderUpdatedEvent.OutputTuple,
    TenderUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VendorBlacklisted"
  ): TypedContractEvent<
    VendorBlacklistedEvent.InputTuple,
    VendorBlacklistedEvent.OutputTuple,
    VendorBlacklistedEvent.OutputObject
  >;
  getEvent(
    key: "VendorRegistered"
  ): TypedContractEvent<
    VendorRegisteredEvent.InputTuple,
    VendorRegisteredEvent.OutputTuple,
    VendorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VendorWhitelisted"
  ): TypedContractEvent<
    VendorWhitelistedEvent.InputTuple,
    VendorWhitelistedEvent.OutputTuple,
    VendorWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerDeclared"
  ): TypedContractEvent<
    WinnerDeclaredEvent.InputTuple,
    WinnerDeclaredEvent.OutputTuple,
    WinnerDeclaredEvent.OutputObject
  >;

  filters: {
    "BidRevealed(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;
    BidRevealed: TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;

    "BidSubmitted(uint256,address,bytes32,uint256)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;

    "OfficerAuthorized(address,uint256)": TypedContractEvent<
      OfficerAuthorizedEvent.InputTuple,
      OfficerAuthorizedEvent.OutputTuple,
      OfficerAuthorizedEvent.OutputObject
    >;
    OfficerAuthorized: TypedContractEvent<
      OfficerAuthorizedEvent.InputTuple,
      OfficerAuthorizedEvent.OutputTuple,
      OfficerAuthorizedEvent.OutputObject
    >;

    "OfficerRevoked(address,uint256)": TypedContractEvent<
      OfficerRevokedEvent.InputTuple,
      OfficerRevokedEvent.OutputTuple,
      OfficerRevokedEvent.OutputObject
    >;
    OfficerRevoked: TypedContractEvent<
      OfficerRevokedEvent.InputTuple,
      OfficerRevokedEvent.OutputTuple,
      OfficerRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "TenderCreated(uint256,address,string,string,uint256,uint256,uint256)": TypedContractEvent<
      TenderCreatedEvent.InputTuple,
      TenderCreatedEvent.OutputTuple,
      TenderCreatedEvent.OutputObject
    >;
    TenderCreated: TypedContractEvent<
      TenderCreatedEvent.InputTuple,
      TenderCreatedEvent.OutputTuple,
      TenderCreatedEvent.OutputObject
    >;

    "TenderEvaluated(uint256,address,uint256,uint256)": TypedContractEvent<
      TenderEvaluatedEvent.InputTuple,
      TenderEvaluatedEvent.OutputTuple,
      TenderEvaluatedEvent.OutputObject
    >;
    TenderEvaluated: TypedContractEvent<
      TenderEvaluatedEvent.InputTuple,
      TenderEvaluatedEvent.OutputTuple,
      TenderEvaluatedEvent.OutputObject
    >;

    "TenderStatusChanged(uint256,uint8,address,uint256)": TypedContractEvent<
      TenderStatusChangedEvent.InputTuple,
      TenderStatusChangedEvent.OutputTuple,
      TenderStatusChangedEvent.OutputObject
    >;
    TenderStatusChanged: TypedContractEvent<
      TenderStatusChangedEvent.InputTuple,
      TenderStatusChangedEvent.OutputTuple,
      TenderStatusChangedEvent.OutputObject
    >;

    "TenderUpdated(uint256,address,string,uint256)": TypedContractEvent<
      TenderUpdatedEvent.InputTuple,
      TenderUpdatedEvent.OutputTuple,
      TenderUpdatedEvent.OutputObject
    >;
    TenderUpdated: TypedContractEvent<
      TenderUpdatedEvent.InputTuple,
      TenderUpdatedEvent.OutputTuple,
      TenderUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VendorBlacklisted(address,string,uint256)": TypedContractEvent<
      VendorBlacklistedEvent.InputTuple,
      VendorBlacklistedEvent.OutputTuple,
      VendorBlacklistedEvent.OutputObject
    >;
    VendorBlacklisted: TypedContractEvent<
      VendorBlacklistedEvent.InputTuple,
      VendorBlacklistedEvent.OutputTuple,
      VendorBlacklistedEvent.OutputObject
    >;

    "VendorRegistered(address,uint256)": TypedContractEvent<
      VendorRegisteredEvent.InputTuple,
      VendorRegisteredEvent.OutputTuple,
      VendorRegisteredEvent.OutputObject
    >;
    VendorRegistered: TypedContractEvent<
      VendorRegisteredEvent.InputTuple,
      VendorRegisteredEvent.OutputTuple,
      VendorRegisteredEvent.OutputObject
    >;

    "VendorWhitelisted(address,uint256)": TypedContractEvent<
      VendorWhitelistedEvent.InputTuple,
      VendorWhitelistedEvent.OutputTuple,
      VendorWhitelistedEvent.OutputObject
    >;
    VendorWhitelisted: TypedContractEvent<
      VendorWhitelistedEvent.InputTuple,
      VendorWhitelistedEvent.OutputTuple,
      VendorWhitelistedEvent.OutputObject
    >;

    "WinnerDeclared(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      WinnerDeclaredEvent.InputTuple,
      WinnerDeclaredEvent.OutputTuple,
      WinnerDeclaredEvent.OutputObject
    >;
    WinnerDeclared: TypedContractEvent<
      WinnerDeclaredEvent.InputTuple,
      WinnerDeclaredEvent.OutputTuple,
      WinnerDeclaredEvent.OutputObject
    >;
  };
}
